//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_book
    {
        [Required (ErrorMessage ="required")]
        public int ID { get; set; }
        [Required(ErrorMessage = "required")]
        public string Title { get; set; }
        [Required(ErrorMessage = "required")]
        public string Author { get; set; }
        [Required(ErrorMessage = "required")]
        public string Year { get; set; }
        [Required(ErrorMessage = "required")]
        public string ISBN { get; set; }
        [Required(ErrorMessage = "required")]
        public string Publisher { get; set; }
        
        
    }
}
